worker_processes 1;

error_log /home/s1156856/error.log;
pid /home/s1156856/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 16856;
        server_name s1156856.student.inf.st.hsleiden.nl;
        access_log /home/s1156856/access.log;

        location / {
            root /home/s1156856/frontend;
            try_files $uri $uri/ /index.html;
        }
    }
}
