worker_processes 1;

error_log logs/error.log;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 4200;
        server_name localhost;
        access_log logs/access.log;

        location / {
            root dist/HomeCinemaProject/browser;
            try_files $uri $uri/ /index.html;
        }
    }
}
